IF OBJECT_ID('mercadopublico.mpp.Comuna', 'U') IS NOT NULL
	DROP TABLE mercadopublico.mpp.Comuna;
GO

CREATE TABLE mercadopublico.mpp.Comuna (
	idComuna int NOT NULL,
	nombre varchar(255),
	idRegion int NOT NULL,
	CONSTRAINT comuna_PK PRIMARY KEY (idComuna)
);
GO

INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1101, 'Iquique', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1107, 'Alto Hospicio', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1401, 'Pozo Almonte', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1402, 'Camiña', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1403, 'Colchane', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1404, 'Huara', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (1405, 'Pica', 1);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2101, 'Antofagasta', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2102, 'Mejillones', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2103, 'Sierra Gorda', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2104, 'Taltal', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2201, 'Calama', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2202, 'Ollagüe', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2203, 'San Pedro de Atacama', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2301, 'Tocopilla', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (2302, 'María Elena', 2);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3101, 'Copiapó', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3102, 'Caldera', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3103, 'Tierra Amarilla', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3201, 'Chañaral', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3202, 'Diego de Almagro', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3301, 'Vallenar', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3302, 'Alto del Carmen', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3303, 'Freirina', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (3304, 'Huasco', 3);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4101, 'La Serena', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4102, 'Coquimbo', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4103, 'Andacollo', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4104, 'La Higuera', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4105, 'Paihuano', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4106, 'Vicuña', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4201, 'Illapel', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4202, 'Canela', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4203, 'Los Vilos', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4204, 'Salamanca', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4301, 'Ovalle', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4302, 'Combarbalá', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4303, 'Monte Patria', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4304, 'Punitaqui', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (4305, 'Río Hurtado', 4);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5101, 'Valparaíso', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5102, 'Casablanca', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5103, 'Concón', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5104, 'Juan Fernández', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5105, 'Puchuncaví', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5107, 'Quintero', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5109, 'Viña del Mar', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5201, 'Isla de Pascua', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5301, 'Los Andes', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5302, 'Calle Larga', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5303, 'Rinconada', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5304, 'San Esteban', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5401, 'La Ligua', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5402, 'Cabildo', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5403, 'Papudo', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5404, 'Petorca', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5405, 'Zapallar', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5501, 'Quillota', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5502, 'La Calera', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5503, 'Hijuelas', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5504, 'La Cruz', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5506, 'Nogales', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5601, 'San Antonio', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5602, 'Algarrobo', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5603, 'Cartagena', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5604, 'El Quisco', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5605, 'El Tabo', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5606, 'Santo Domingo', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5701, 'San Felipe', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5702, 'Catemu', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5703, 'Llay-Llay', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5704, 'Panquehue', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5705, 'Putaendo', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5706, 'Santa María', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5801, 'Quilpué', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5802, 'Limache', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5803, 'Olmué', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (5804, 'Villa Alemana', 5);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6101, 'Rancagua', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6102, 'Codegua', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6103, 'Coinco', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6104, 'Coltauco', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6105, 'Doñihue', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6106, 'Graneros', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6107, 'Las Cabras', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6108, 'Machalí', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6109, 'Malloa', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6110, 'Mostazal', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6111, 'Olivar', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6112, 'Peumo', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6113, 'Pichidegua', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6114, 'Quinta de Tilcoco', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6115, 'Rengo', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6116, 'Requínoa', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6117, 'San Vicente', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6201, 'Pichilemu', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6202, 'La Estrella', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6203, 'Litueche', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6204, 'Marchihue', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6205, 'Navidad', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6206, 'Paredones', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6301, 'San Fernando', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6302, 'Chépica', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6303, 'Chimbarongo', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6304, 'Lolol', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6305, 'Nancagua', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6306, 'Palmilla', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6307, 'Peralillo', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6308, 'Placilla', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6309, 'Pumanque', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (6310, 'Santa Cruz', 6);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7101, 'Talca', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7102, 'Constitución', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7103, 'Curepto', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7104, 'Empedrado', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7105, 'Maule', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7106, 'Pelarco', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7107, 'Pencahue', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7108, 'Río Claro', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7109, 'San Clemente', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7110, 'San Rafael', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7201, 'Cauquenes', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7202, 'Chanco', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7203, 'Pelluhue', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7301, 'Curicó', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7302, 'Hualañé', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7303, 'Licantén', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7304, 'Molina', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7305, 'Rauco', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7306, 'Romeral', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7307, 'Sagrada Familia', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7308, 'Teno', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7309, 'Vichuquén', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7401, 'Linares', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7402, 'Colbún', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7403, 'Longaví', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7404, 'Parral', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7405, 'Retiro', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7406, 'San Javier', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7407, 'Villa Alegre', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (7408, 'Yerbas Buenas', 7);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8101, 'Concepción', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8102, 'Coronel', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8103, 'Chiguayante', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8104, 'Florida', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8105, 'Hualqui', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8106, 'Lota', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8107, 'Penco', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8108, 'San Pedro de La Paz', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8109, 'Santa Juana', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8110, 'Talcahuano', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8111, 'Tomé', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8112, 'Hualpén', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8201, 'Lebu', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8202, 'Arauco', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8203, 'Cañete', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8204, 'Contulmo', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8205, 'Curanilahue', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8206, 'Los Álamos', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8207, 'Tirúa', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8301, 'Los Ángeles', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8302, 'Antuco', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8303, 'Cabrero', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8304, 'Laja', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8305, 'Mulchén', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8306, 'Nacimiento', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8307, 'Negrete', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8308, 'Quilaco', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8309, 'Quilleco', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8310, 'San Rosendo', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8311, 'Santa Bárbara', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8312, 'Tucapel', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8313, 'Yumbel', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (8314, 'Alto Biobío', 8);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9101, 'Temuco', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9102, 'Carahue', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9103, 'Cunco', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9104, 'Curarrehue', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9105, 'Freire', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9106, 'Galvarino', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9107, 'Gorbea', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9108, 'Lautaro', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9109, 'Loncoche', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9110, 'Melipeuco', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9111, 'Nueva Imperial', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9112, 'Padre Las Casas', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9113, 'Perquenco', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9114, 'Pitrufquén', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9115, 'Pucón', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9116, 'Saavedra', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9117, 'Teodoro Schmidt', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9118, 'Toltén', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9119, 'Vilcún', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9120, 'Villarrica', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9121, 'Cholchol', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9201, 'Angol', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9202, 'Collipulli', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9203, 'Curacautín', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9204, 'Ercilla', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9205, 'Lonquimay', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9206, 'Los Sauces', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9207, 'Lumaco', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9208, 'Purén', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9209, 'Renaico', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9210, 'Traiguén', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (9211, 'Victoria', 9);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10101, 'Puerto Montt', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10102, 'Calbuco', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10103, 'Cochamó', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10104, 'Fresia', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10105, 'Frutillar', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10106, 'Los Muermos', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10107, 'Llanquihue', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10108, 'Maullín', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10109, 'Puerto Varas', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10201, 'Castro', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10202, 'Ancud', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10203, 'Chonchi', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10204, 'Curaco de Vélez', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10205, 'Dalcahue', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10206, 'Puqueldón', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10207, 'Queilén', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10208, 'Quellón', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10209, 'Quemchi', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10210, 'Quinchao', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10301, 'Osorno', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10302, 'Puerto Octay', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10303, 'Purranque', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10304, 'Puyehue', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10305, 'Río Negro', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10306, 'San Juan de la Costa', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10307, 'San Pablo', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10401, 'Chaitén', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10402, 'Futaleufú', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10403, 'Hualaihué', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (10404, 'Palena', 10);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11101, 'Coyhaique', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11102, 'Lago Verde', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11201, 'Aysén', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11202, 'Cisnes', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11203, 'Guaitecas', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11301, 'Cochrane', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11302, 'O''Higgins', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11303, 'Tortel', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11401, 'Chile Chico', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (11402, 'Río Ibáñez', 11);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12101, 'Punta Arenas', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12102, 'Laguna Blanca', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12103, 'Río Verde', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12104, 'San Gregorio', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12201, 'Cabo de Hornos', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12202, 'Antártica', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12301, 'Porvenir', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12302, 'Primavera', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12303, 'Timaukel', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12401, 'Natales', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (12402, 'Torres del Paine', 12);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13101, 'Santiago', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13102, 'Cerrillos', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13103, 'Cerro Navia', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13104, 'Conchalí', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13105, 'El Bosque', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13106, 'Estación Central', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13107, 'Huechuraba', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13108, 'Independencia', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13109, 'La Cisterna', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13110, 'La Florida', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13111, 'La Granja', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13112, 'La Pintana', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13113, 'La Reina', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13114, 'Las Condes', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13115, 'Lo Barnechea', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13116, 'Lo Espejo', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13117, 'Lo Prado', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13118, 'Macul', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13119, 'Maipú', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13120, 'Ñuñoa', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13121, 'Pedro Aguirre Cerda', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13122, 'Peñalolén', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13123, 'Providencia', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13124, 'Pudahuel', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13125, 'Quilicura', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13126, 'Quinta Normal', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13127, 'Recoleta', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13128, 'Renca', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13129, 'San Joaquín', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13130, 'San Miguel', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13131, 'San Ramón', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13132, 'Vitacura', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13201, 'Puente Alto', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13202, 'Pirque', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13203, 'San José de Maipo', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13301, 'Colina', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13302, 'Lampa', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13303, 'Til Til', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13401, 'San Bernardo', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13402, 'Buin', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13403, 'Calera de Tango', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13404, 'Paine', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13501, 'Melipilla', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13502, 'Alhué', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13503, 'Curacaví', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13504, 'María Pinto', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13505, 'San Pedro', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13601, 'Talagante', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13602, 'El Monte', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13603, 'Isla de Maipo', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13604, 'Padre Hurtado', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (13605, 'Peñaflor', 13);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14101, 'Valdivia', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14102, 'Corral', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14103, 'Lanco', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14104, 'Los Lagos', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14105, 'Máfil', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14106, 'Mariquina', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14107, 'Paillaco', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14108, 'Panguipulli', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14201, 'La Unión', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14202, 'Futrono', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14203, 'Lago Ranco', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (14204, 'Río Bueno', 14);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (15101, 'Arica', 15);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (15102, 'Camarones', 15);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (15201, 'Putre', 15);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (15202, 'General Lagos', 15);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16101, 'Chillán', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16102, 'Bulnes', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16103, 'Chillán Viejo', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16104, 'El Carmen', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16105, 'Pemuco', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16106, 'Pinto', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16107, 'Quillón', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16108, 'San Ignacio', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16109, 'Yungay', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16201, 'Quirihue', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16202, 'Cobquecura', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16203, 'Coelemu', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16204, 'Ninhue', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16205, 'Portezuelo', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16206, 'Ránquil', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16207, 'Treguaco', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16301, 'San Carlos', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16302, 'Coihueco', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16303, 'Ñiquén', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16304, 'San Fabián', 16);
INSERT INTO mercadopublico.mpp.Comuna (idComuna, nombre, idRegion) VALUES (16305, 'San Nicolás', 16);
