DROP TABLE IF EXISTS mp_estrella_db.dbo.dim_zona;

CREATE TABLE mp_estrella_db.dbo.dim_zona (
    id_zona            int not null,
	comuna             varchar(100) not null,
	provincia          varchar(100) not null,
	region             varchar(100) not null,
	numero_region      int,
	CONSTRAINT PK_zona PRIMARY KEY (id_zona)
);

INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (0, 'Extranjero', 'Extranjero', 'Extranjero');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1000, '', 'Iquique', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2000, '', 'Antofagasta', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3000, '', 'Copiapó', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4000, '', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5000, '', 'Marga Marga', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6000, '', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7000, '', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8000, '', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9000, '', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10000, '', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12000, '', 'Última Esperanza', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11000, '', 'General Carrera', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13000, '', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14000, '', 'Ranco', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (15000, '', 'Arica', 'Arica y Parinacota');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16000, '', 'Diguillín', 'Ñuble');

INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (15101, 'Arica', 'Arica', 'Arica y Parinacota');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (15102, 'Camarones', 'Arica', 'Arica y Parinacota');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (15201, 'Putre', 'Parinacota', 'Arica y Parinacota');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (15202, 'General Lagos', 'Parinacota', 'Arica y Parinacota');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1101, 'Iquique', 'Iquique', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1107, 'Alto Hospicio', 'Iquique', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1401, 'Pozo Almonte', 'Tamarugal', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1402, 'Camiña', 'Tamarugal', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1403, 'Colchane', 'Tamarugal', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1404, 'Huara', 'Tamarugal', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (1405, 'Pica', 'Tamarugal', 'Tarapacá');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2101, 'Antofagasta', 'Antofagasta', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2102, 'Mejillones', 'Antofagasta', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2103, 'Sierra Gorda', 'Antofagasta', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2104, 'Taltal', 'Antofagasta', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2201, 'Calama', 'El Loa', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2202, 'Ollagüe', 'El Loa', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2203, 'San Pedro de Atacama', 'El Loa', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2301, 'Tocopilla', 'Tocopilla', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (2302, 'María Elena', 'Tocopilla', 'Antofagasta');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3101, 'Copiapó', 'Copiapó', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3102, 'Caldera', 'Copiapó', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3103, 'Tierra Amarilla', 'Copiapó', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3201, 'Chañaral', 'Chañaral', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3202, 'Diego de Almagro', 'Chañaral', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3301, 'Vallenar', 'Huasco', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3302, 'Alto del Carmen', 'Huasco', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3303, 'Freirina', 'Huasco', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (3304, 'Huasco', 'Huasco', 'Atacama');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4101, 'La Serena', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4102, 'Coquimbo', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4103, 'Andacollo', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4104, 'La Higuera', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4105, 'Paihuano', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4106, 'Vicuña', 'Elqui', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4201, 'Illapel', 'Choapa', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4202, 'Canela', 'Choapa', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4203, 'Los Vilos', 'Choapa', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4204, 'Salamanca', 'Choapa', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4301, 'Ovalle', 'Limarí', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4302, 'Combarbalá', 'Limarí', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4303, 'Monte Patria', 'Limarí', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4304, 'Punitaqui', 'Limarí', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (4305, 'Río Hurtado', 'Limarí', 'Coquimbo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5101, 'Valparaíso', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5102, 'Casablanca', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5103, 'Concón', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5104, 'Juan Fernández', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5105, 'Puchuncaví', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5107, 'Quintero', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5109, 'Viña del Mar', 'Valparaíso', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5201, 'Isla de Pascua', 'Isla de Pascua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5301, 'Los Andes', 'Los Andes', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5302, 'Calle Larga', 'Los Andes', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5303, 'Rinconada', 'Los Andes', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5304, 'San Esteban', 'Los Andes', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5401, 'La Ligua', 'Petorca', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5402, 'Cabildo', 'Petorca', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5403, 'Papudo', 'Petorca', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5404, 'Petorca', 'Petorca', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5405, 'Zapallar', 'Petorca', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5501, 'Quillota', 'Quillota', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5502, 'La Calera', 'Quillota', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5503, 'Hijuelas', 'Quillota', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5504, 'La Cruz', 'Quillota', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5506, 'Nogales', 'Quillota', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5601, 'San Antonio', 'San Antonio', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5602, 'Algarrobo', 'San Antonio', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5603, 'Cartagena', 'San Antonio', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5604, 'El Quisco', 'San Antonio', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5605, 'El Tabo', 'San Antonio', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5606, 'Santo Domingo', 'San Antonio', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5701, 'San Felipe', 'San Felipe de Aconcagua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5702, 'Catemu', 'San Felipe de Aconcagua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5703, 'Llay-Llay', 'San Felipe de Aconcagua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5704, 'Panquehue', 'San Felipe de Aconcagua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5705, 'Putaendo', 'San Felipe de Aconcagua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5706, 'Santa María', 'San Felipe de Aconcagua', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5801, 'Quilpué', 'Marga Marga', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5802, 'Limache', 'Marga Marga', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5803, 'Olmué', 'Marga Marga', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (5804, 'Villa Alemana', 'Marga Marga', 'Valparaíso');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6101, 'Rancagua', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6102, 'Codegua', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6103, 'Coinco', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6104, 'Coltauco', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6105, 'Doñihue', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6106, 'Graneros', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6107, 'Las Cabras', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6108, 'Machalí', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6109, 'Malloa', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6110, 'Mostazal', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6111, 'Olivar', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6112, 'Peumo', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6113, 'Pichidegua', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6114, 'Quinta de Tilcoco', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6115, 'Rengo', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6116, 'Requínoa', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6117, 'San Vicente', 'Cachapoal', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6201, 'Pichilemu', 'Cardenal Caro', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6202, 'La Estrella', 'Cardenal Caro', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6203, 'Litueche', 'Cardenal Caro', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6204, 'Marchihue', 'Cardenal Caro', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6205, 'Navidad', 'Cardenal Caro', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6206, 'Paredones', 'Cardenal Caro', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6301, 'San Fernando', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6302, 'Chépica', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6303, 'Chimbarongo', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6304, 'Lolol', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6305, 'Nancagua', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6306, 'Palmilla', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6307, 'Peralillo', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6308, 'Placilla', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6309, 'Pumanque', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (6310, 'Santa Cruz', 'Colchagua', 'Lib. Gral. Bernardo O''Higgins');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7101, 'Talca', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7102, 'Constitución', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7103, 'Curepto', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7104, 'Empedrado', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7105, 'Maule', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7106, 'Pelarco', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7107, 'Pencahue', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7108, 'Río Claro', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7109, 'San Clemente', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7110, 'San Rafael', 'Talca', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7201, 'Cauquenes', 'Cauquenes', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7202, 'Chanco', 'Cauquenes', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7203, 'Pelluhue', 'Cauquenes', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7301, 'Curicó', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7302, 'Hualañé', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7303, 'Licantén', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7304, 'Molina', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7305, 'Rauco', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7306, 'Romeral', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7307, 'Sagrada Familia', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7308, 'Teno', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7309, 'Vichuquén', 'Curicó', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7401, 'Linares', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7402, 'Colbún', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7403, 'Longaví', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7404, 'Parral', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7405, 'Retiro', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7406, 'San Javier', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7407, 'Villa Alegre', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (7408, 'Yerbas Buenas', 'Linares', 'Maule');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16101, 'Chillán', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16102, 'Bulnes', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16103, 'Chillán Viejo', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16104, 'El Carmen', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16105, 'Pemuco', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16106, 'Pinto', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16107, 'Quillón', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16108, 'San Ignacio', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16109, 'Yungay', 'Diguillín', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16201, 'Quirihue', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16202, 'Cobquecura', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16203, 'Coelemu', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16204, 'Ninhue', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16205, 'Portezuelo', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16206, 'Ránquil', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16207, 'Treguaco', 'Itata', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16301, 'San Carlos', 'Punilla', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16302, 'Coihueco', 'Punilla', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16303, 'Ñiquén', 'Punilla', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16304, 'San Fabián', 'Punilla', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (16305, 'San Nicolás', 'Punilla', 'Ñuble');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8101, 'Concepción', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8102, 'Coronel', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8103, 'Chiguayante', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8104, 'Florida', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8105, 'Hualqui', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8106, 'Lota', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8107, 'Penco', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8108, 'San Pedro de La Paz', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8109, 'Santa Juana', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8110, 'Talcahuano', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8111, 'Tomé', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8112, 'Hualpén', 'Concepción', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8201, 'Lebu', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8202, 'Arauco', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8203, 'Cañete', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8204, 'Contulmo', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8205, 'Curanilahue', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8206, 'Los Álamos', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8207, 'Tirúa', 'Arauco', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8301, 'Los Ángeles', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8302, 'Antuco', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8303, 'Cabrero', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8304, 'Laja', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8305, 'Mulchén', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8306, 'Nacimiento', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8307, 'Negrete', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8308, 'Quilaco', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8309, 'Quilleco', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8310, 'San Rosendo', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8311, 'Santa Bárbara', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8312, 'Tucapel', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8313, 'Yumbel', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (8314, 'Alto Biobío', 'Biobío', 'Biobío');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9101, 'Temuco', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9102, 'Carahue', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9103, 'Cunco', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9104, 'Curarrehue', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9105, 'Freire', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9106, 'Galvarino', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9107, 'Gorbea', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9108, 'Lautaro', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9109, 'Loncoche', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9110, 'Melipeuco', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9111, 'Nueva Imperial', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9112, 'Padre Las Casas', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9113, 'Perquenco', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9114, 'Pitrufquén', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9115, 'Pucón', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9116, 'Saavedra', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9117, 'Teodoro Schmidt', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9118, 'Toltén', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9119, 'Vilcún', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9120, 'Villarrica', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9121, 'Cholchol', 'Cautín', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9201, 'Angol', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9202, 'Collipulli', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9203, 'Curacautín', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9204, 'Ercilla', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9205, 'Lonquimay', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9206, 'Los Sauces', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9207, 'Lumaco', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9208, 'Purén', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9209, 'Renaico', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9210, 'Traiguén', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (9211, 'Victoria', 'Malleco', 'La Araucanía');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14101, 'Valdivia', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14102, 'Corral', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14103, 'Lanco', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14104, 'Los Lagos', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14105, 'Máfil', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14106, 'Mariquina', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14107, 'Paillaco', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14108, 'Panguipulli', 'Valdivia', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14201, 'La Unión', 'Ranco', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14202, 'Futrono', 'Ranco', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14203, 'Lago Ranco', 'Ranco', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (14204, 'Río Bueno', 'Ranco', 'Los Ríos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10101, 'Puerto Montt', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10102, 'Calbuco', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10103, 'Cochamó', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10104, 'Fresia', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10105, 'Frutillar', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10106, 'Los Muermos', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10107, 'Llanquihue', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10108, 'Maullín', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10109, 'Puerto Varas', 'Llanquihue', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10201, 'Castro', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10202, 'Ancud', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10203, 'Chonchi', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10204, 'Curaco de Vélez', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10205, 'Dalcahue', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10206, 'Puqueldón', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10207, 'Queilén', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10208, 'Quellón', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10209, 'Quemchi', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10210, 'Quinchao', 'Chiloé', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10301, 'Osorno', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10302, 'Puerto Octay', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10303, 'Purranque', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10304, 'Puyehue', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10305, 'Río Negro', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10306, 'San Juan de la Costa', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10307, 'San Pablo', 'Osorno', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10401, 'Chaitén', 'Palena', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10402, 'Futaleufú', 'Palena', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10403, 'Hualaihué', 'Palena', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (10404, 'Palena', 'Palena', 'Los Lagos');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11101, 'Coyhaique', 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11102, 'Lago Verde', 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11201, 'Aysén', 'Aysén', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11202, 'Cisnes', 'Aysén', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11203, 'Guaitecas', 'Aysén', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11301, 'Cochrane', 'Capitán Prat', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11302, 'O''Higgins', 'Capitán Prat', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11303, 'Tortel', 'Capitán Prat', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11401, 'Chile Chico', 'General Carrera', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (11402, 'Río Ibáñez', 'General Carrera', 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12101, 'Punta Arenas', 'Magallanes', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12102, 'Laguna Blanca', 'Magallanes', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12103, 'Río Verde', 'Magallanes', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12104, 'San Gregorio', 'Magallanes', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12201, 'Cabo de Hornos', 'Antártica Chilena', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12202, 'Antártica', 'Antártica Chilena', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12301, 'Porvenir', 'Tierra del Fuego', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12302, 'Primavera', 'Tierra del Fuego', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12303, 'Timaukel', 'Tierra del Fuego', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12401, 'Natales', 'Última Esperanza', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (12402, 'Torres del Paine', 'Última Esperanza', 'Magallanes y Antártica Chilena');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13101, 'Santiago', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13102, 'Cerrillos', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13103, 'Cerro Navia', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13104, 'Conchalí', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13105, 'El Bosque', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13106, 'Estación Central', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13107, 'Huechuraba', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13108, 'Independencia', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13109, 'La Cisterna', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13110, 'La Florida', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13111, 'La Granja', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13112, 'La Pintana', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13113, 'La Reina', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13114, 'Las Condes', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13115, 'Lo Barnechea', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13116, 'Lo Espejo', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13117, 'Lo Prado', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13118, 'Macul', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13119, 'Maipú', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13120, 'Ñuñoa', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13121, 'Pedro Aguirre Cerda', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13122, 'Peñalolén', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13123, 'Providencia', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13124, 'Pudahuel', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13125, 'Quilicura', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13126, 'Quinta Normal', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13127, 'Recoleta', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13128, 'Renca', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13129, 'San Joaquín', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13130, 'San Miguel', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13131, 'San Ramón', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13132, 'Vitacura', 'Santiago', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13201, 'Puente Alto', 'Cordillera', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13202, 'Pirque', 'Cordillera', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13203, 'San José de Maipo', 'Cordillera', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13301, 'Colina', 'Chacabuco', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13302, 'Lampa', 'Chacabuco', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13303, 'Til Til', 'Chacabuco', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13401, 'San Bernardo', 'Maipo', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13402, 'Buin', 'Maipo', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13403, 'Calera de Tango', 'Maipo', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13404, 'Paine', 'Maipo', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13501, 'Melipilla', 'Melipilla', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13502, 'Alhué', 'Melipilla', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13503, 'Curacaví', 'Melipilla', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13504, 'María Pinto', 'Melipilla', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13505, 'San Pedro', 'Melipilla', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13601, 'Talagante', 'Talagante', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13602, 'El Monte', 'Talagante', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13603, 'Isla de Maipo', 'Talagante', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13604, 'Padre Hurtado', 'Talagante', 'Metropolitana de Santiago');
INSERT INTO mp_estrella_db.dbo.dim_zona (id_zona, comuna, provincia, region) VALUES (13605, 'Peñaflor', 'Talagante', 'Metropolitana de Santiago');

UPDATE mp_estrella_db.dbo.dim_zona
   SET numero_region = FLOOR(id_zona / 1000);